spring:
  application:
    name: retail-hub-orders
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8083
  servlet:
    context-path: /v1/orders

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

